image: docker:latest

services:
  - docker:dind


stages:
  - test
before_script:
  - docker info



build_image:
  stage: test
  script:
    - apk add --no-cache docker-compose
    - docker-compose up --exit-code-from tests
