FROM python:latest

WORKDIR /app

COPY poetry.lock .
COPY pyproject.toml .


COPY /app .

RUN pip install poetry


RUN poetry config virtualenvs.create false && poetry install



CMD ["python","-m","pytest"]
